# Generated by Django 4.2.29 on 2026-03-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proyecto_motivo_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('SOLICITUD', 'Solicitud'), ('DESPIECE', 'Despiece'), ('EN_REVISION_COMPRAS', 'En revisión de precios (Compras)'), ('DESPIECE_VALIDADO', 'Despiece validado'), ('APU', 'APU en proceso'), ('APU_GENERADO', 'APU enviado a revisión'), ('COTIZADO', 'Cotizado'), ('APROBADO', 'Aprobado'), ('CERRADO', 'Cerrado'), ('ANULADO', 'Anulado')], default='SOLICITUD', max_length=25),
        ),
    ]
