# Generated by Django 4.2.29 on 2026-03-13 17:43
# Manually augmented: adds data migration to backfill categoria_producto
# from producto.categoria for existing ReglaCalculo and DependenciaTecnica records.

from django.db import migrations, models
import django.db.models.deletion


def backfill_categoria_producto(apps, schema_editor):
    """
    Para todos los registros existentes donde hay producto concreto asignado,
    copia producto.categoria → categoria_producto.
    Esto garantiza que el campo siempre refleje la categoría correcta.
    """
    ReglaCalculo = apps.get_model("core", "ReglaCalculo")
    DependenciaTecnica = apps.get_model("core", "DependenciaTecnica")
    DespieceLinea = apps.get_model("core", "DespieceLinea")

    # ReglaCalculo: copiar producto.categoria → categoria_producto
    for rc in ReglaCalculo.objects.filter(producto__isnull=False, categoria_producto__isnull=True).select_related("producto__categoria"):
        rc.categoria_producto = rc.producto.categoria
        rc.save(update_fields=["categoria_producto"])

    # DependenciaTecnica: copiar producto_dependiente.categoria → categoria_producto
    for dt in DependenciaTecnica.objects.filter(producto_dependiente__isnull=False, categoria_producto__isnull=True).select_related("producto_dependiente__categoria"):
        dt.categoria_producto = dt.producto_dependiente.categoria
        dt.save(update_fields=["categoria_producto"])

    # DespieceLinea: copiar producto.categoria → categoria_producto
    for dl in DespieceLinea.objects.filter(producto__isnull=False, categoria_producto__isnull=True).select_related("producto__categoria"):
        dl.categoria_producto = dl.producto.categoria
        dl.save(update_fields=["categoria_producto"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependenciatecnica',
            name='categoria_producto',
            field=models.ForeignKey(blank=True, help_text='Categoría cuando el producto se elegirá por proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencias_tecnicas', to='core.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='dependenciatecnica',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre descriptivo (obligatorio para dependencias basadas en categoría)', max_length=200),
        ),
        migrations.AddField(
            model_name='despiecelinea',
            name='categoria_producto',
            field=models.ForeignKey(blank=True, help_text='Categoría cuando el producto aún no ha sido seleccionado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despiece_lineas', to='core.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='despiecelinea',
            name='dependencia_tecnica',
            field=models.ForeignKey(blank=True, help_text='Dependencia que originó esta línea (para líneas automáticas de categoría)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despiece_lineas', to='core.dependenciatecnica'),
        ),
        migrations.AddField(
            model_name='reglacalculo',
            name='categoria_producto',
            field=models.ForeignKey(blank=True, help_text='Categoría del producto cuando no hay producto específico asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_calculo', to='core.categoriaproducto'),
        ),
        migrations.AlterField(
            model_name='dependenciatecnica',
            name='producto_dependiente',
            field=models.ForeignKey(blank=True, help_text='Producto concreto (opcional; use categoría para dependencias genéricas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencias_dependiente', to='core.producto'),
        ),
        migrations.AlterField(
            model_name='despiecelinea',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto resuelto; NULL si aún está pendiente de selección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despiece_lineas', to='core.producto'),
        ),
        migrations.AlterField(
            model_name='reglacalculo',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto específico (opcional; use categoría si el producto se elige por proyecto)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_calculo', to='core.producto'),
        ),
        # ── Data migration: backfill categoria_producto from producto.categoria ─
        migrations.RunPython(
            backfill_categoria_producto,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
