# Generated by Django 4.2.29 on 2026-03-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_falke8_categoria_componentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglacalculo',
            name='obligatoria',
            field=models.BooleanField(default=True, help_text='Si es False, el componente puede omitirse en el despiece de un proyecto'),
        ),
        migrations.AddField(
            model_name='reglacalculo',
            name='variable_salida',
            field=models.CharField(blank=True, help_text="Nombre con el que el resultado de esta regla queda disponible en el contexto para reglas derivadas. Ej: 'Limpiador' → permite que Estopa use formula_python='Limpiador / 2'", max_length=80),
        ),
    ]
