# Generated by Django 4.2.29 on 2026-03-19 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0001_initial'),
        ('catalogos', '0001_initial'),
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despiecelinea',
            options={'ordering': ['proyecto_sistema', 'es_dependencia_automatica', 'id'], 'verbose_name': 'Línea de Despiece', 'verbose_name_plural': 'Líneas de Despiece'},
        ),
        migrations.AlterModelOptions(
            name='proyectosistema',
            options={'verbose_name': 'Ejecución de Sistema', 'verbose_name_plural': 'Ejecuciones de Sistemas'},
        ),
        migrations.AlterField(
            model_name='despiecelinea',
            name='cantidad_ajustada',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Valor manual que reemplaza al calculado si el usuario lo ajusta.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='despiecelinea',
            name='categoria_producto',
            field=models.ForeignKey(blank=True, help_text='Categoría cuando el producto aún no ha sido seleccionado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despiece_lineas', to='catalogos.categoriaproducto'),
        ),
        migrations.AlterField(
            model_name='despiecelinea',
            name='dependencia_tecnica',
            field=models.ForeignKey(blank=True, help_text='Dependencia que originó esta línea (líneas automáticas).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despiece_lineas', to='ingenieria.dependenciatecnica'),
        ),
        migrations.AlterField(
            model_name='despiecelinea',
            name='precio_snapshot',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Precio unitario capturado al momento de calcular el despiece.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='despiecelinea',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto resuelto; NULL si aún está pendiente de selección.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despiece_lineas', to='catalogos.producto'),
        ),
        migrations.AlterField(
            model_name='despiecelinea',
            name='regla',
            field=models.ForeignKey(blank=True, help_text='Regla de cálculo que generó esta línea.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despiece_lineas', to='ingenieria.reglacalculo'),
        ),
        migrations.AlterField(
            model_name='proyectosistema',
            name='parametros_entrada',
            field=models.JSONField(blank=True, default=dict, help_text="Variables de entrada específicas de este sistema. Ej: {'total_powergrip': 2883} ó {'ml_fachada': 120, 'altura_m': 4}"),
        ),
    ]
