# Generated by Django 4.2.29 on 2026-03-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('ingenieria', '0002_alter_dependenciatecnica_categoria_producto_and_more'),
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apulinea',
            name='despiece_linea',
            field=models.ForeignKey(blank=True, help_text='Referencia al ítem de despiece origen (solo materiales)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apu_lineas', to='presupuestos.despiecelinea'),
        ),
        migrations.AlterField(
            model_name='apulinea',
            name='editable',
            field=models.BooleanField(default=False, help_text='Si True, el usuario puede modificar precio_referencia/rendimiento'),
        ),
        migrations.AlterField(
            model_name='apulinea',
            name='precio_referencia',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Precio unitario del insumo/recurso', max_digits=18),
        ),
        migrations.AlterField(
            model_name='apulinea',
            name='rendimiento',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Cantidad de producto que rinde por unidad de APU', max_digits=14),
        ),
        migrations.AlterField(
            model_name='apuproyecto',
            name='factor_venta_pct',
            field=models.DecimalField(decimal_places=4, default=20, help_text='% margen sobre costo unitario → valor unitario', max_digits=8),
        ),
        migrations.AlterField(
            model_name='despiecelinea',
            name='categoria_producto',
            field=models.ForeignKey(blank=True, help_text='Categoría cuando el producto aún no ha sido seleccionado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despiece_lineas', to='catalogos.categoriaproducto'),
        ),
        migrations.AlterField(
            model_name='despiecelinea',
            name='dependencia_tecnica',
            field=models.ForeignKey(blank=True, help_text='Dependencia que originó esta línea (para líneas automáticas de categoría)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despiece_lineas', to='ingenieria.dependenciatecnica'),
        ),
        migrations.AlterField(
            model_name='despiecelinea',
            name='precio_snapshot',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Precio unitario al momento de calcular el despiece', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='despiecelinea',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto resuelto; NULL si aún está pendiente de selección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despiece_lineas', to='catalogos.producto'),
        ),
        migrations.AlterField(
            model_name='proyectosistema',
            name='cuadrilla_personas',
            field=models.IntegerField(blank=True, help_text='Número de personas en la cuadrilla de instalación', null=True),
        ),
        migrations.AlterField(
            model_name='proyectosistema',
            name='total_powergip',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad base de PowerGrip ingresada por el usuario', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='proyectosistema',
            name='variables_extra',
            field=models.JSONField(blank=True, default=dict, help_text='Variables adicionales editables por proyecto en formato JSON'),
        ),
    ]
