# Generated by Django 4.2.29 on 2026-03-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItemAPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_apu', models.CharField(choices=[('MATERIALES', 'Materiales'), ('HERRAMIENTAS_EQUIPOS', 'Herramientas y equipos'), ('TRANSPORTE', 'Transporte'), ('MANO_DE_OBRA', 'Mano de obra'), ('ADMINISTRACION', 'Administración')], help_text='Tipo de APU al que pertenecen los ítems de esta categoría.', max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la UI')),
            ],
            options={
                'verbose_name': 'Categoría de ítem APU',
                'verbose_name_plural': 'Categorías de ítems APU',
                'db_table': 'catalogo_apu_categorias',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuadrillaPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preset de cuadrilla',
                'verbose_name_plural': 'Presets de cuadrilla',
                'db_table': 'cuadrilla_presets',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemCatalogoAPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(decimal_places=4, default=0, help_text='Salario/precio base del ítem ($/unidad de tiempo).', max_digits=18)),
                ('unidad', models.CharField(choices=[('dia', 'Día'), ('mes', 'Mes'), ('hora', 'Hora'), ('und', 'Unidad'), ('global', 'Global')], default='dia', help_text='Unidad sobre la que aplica el precio base.', max_length=20)),
                ('vida_util_dias', models.PositiveIntegerField(blank=True, help_text='Vida útil en días. Solo para herramientas/equipos — permite calcular depreciación por jornada.', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='presupuestos.categoriaitemapu')),
            ],
            options={
                'verbose_name': 'Ítem de catálogo APU',
                'verbose_name_plural': 'Ítems de catálogo APU',
                'db_table': 'catalogo_apu_items',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuadrillaPresetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuadrilla_uses', to='presupuestos.itemcatalogoapu')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='presupuestos.cuadrillapreset')),
            ],
            options={
                'verbose_name': 'Ítem de cuadrilla preset',
                'verbose_name_plural': 'Ítems de cuadrilla preset',
                'db_table': 'cuadrilla_preset_items',
                'unique_together': {('preset', 'item')},
            },
        ),
    ]
