# Generated by Django 4.2.29 on 2026-03-19 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0001_initial'),
        ('presupuestos', '0002_alter_despiecelinea_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despiecelinea',
            options={'ordering': ['proyecto_sistema', 'id'], 'verbose_name': 'Línea de Despiece', 'verbose_name_plural': 'Líneas de Despiece'},
        ),
        migrations.AddField(
            model_name='despiecelinea',
            name='componente_codigo',
            field=models.CharField(blank=True, db_index=True, help_text="Código del componente según la definición backend del sistema (system_defs). Ej: 'fijaciones_u7', 'limpiador_plus'.", max_length=80),
        ),
        migrations.AlterField(
            model_name='despiecelinea',
            name='dependencia_tecnica',
            field=models.ForeignKey(blank=True, help_text='[LEGADO] Dependencia automática en el flujo anterior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despiece_lineas', to='ingenieria.dependenciatecnica'),
        ),
        migrations.AlterField(
            model_name='despiecelinea',
            name='regla',
            field=models.ForeignKey(blank=True, help_text='[LEGADO] Regla que generó esta línea en el flujo anterior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despiece_lineas', to='ingenieria.reglacalculo'),
        ),
        migrations.AlterField(
            model_name='proyectosistema',
            name='parametros_entrada',
            field=models.JSONField(blank=True, default=dict, help_text="Variables de entrada específicas de este sistema. Ej: {'total_powergrip': 2883, 'tornilleria_u7': 8, 'desperdicio': 1.01}"),
        ),
    ]
