# Generated by Django 4.2.29 on 2026-03-30 19:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_apu_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apulinea',
            name='costo_por_dia',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Precio_referencia / vida_util_dias. Calculado automáticamente.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='apulinea',
            name='costo_total',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='rendimiento × costo_unitario.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='apulinea',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='precio_referencia × IVA_factor.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='apulinea',
            name='despiece_linea',
            field=models.ForeignKey(blank=True, help_text='Ítem del despiece de materiales (solo para tipo MATERIALES).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apu_lineas', to='presupuestos.despiecelinea'),
        ),
        migrations.AlterField(
            model_name='apulinea',
            name='editable',
            field=models.BooleanField(default=False, help_text='Si True, el usuario puede modificar precio_referencia y rendimiento.'),
        ),
        migrations.AlterField(
            model_name='apulinea',
            name='iva_aplicado',
            field=models.BooleanField(default=True, help_text='Si True, se multiplica precio_referencia por el factor IVA del APU.'),
        ),
        migrations.AlterField(
            model_name='apulinea',
            name='precio_referencia',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Precio unitario del insumo/recurso (sin IVA).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='apulinea',
            name='rendimiento',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='Cantidad del recurso necesaria por unidad de APU.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='apulinea',
            name='tipo',
            field=models.CharField(choices=[('MATERIALES', 'Materiales'), ('HERRAMIENTAS_EQUIPOS', 'Herramientas y equipos'), ('TRANSPORTE', 'Transporte'), ('MANO_DE_OBRA', 'Mano de obra'), ('ADMINISTRACION', 'Administración')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='apulinea',
            name='valor_total',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='rendimiento × valor_unitario.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='apulinea',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='costo_unitario × (1 + factor_venta_pct / 100).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='apulinea',
            name='vida_util_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Vida útil en días (herramientas/dotación). Permite mostrar el costo por jornada en reportes.', null=True),
        ),
        migrations.AlterField(
            model_name='categoriaitemapu',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden en la UI.'),
        ),
        migrations.AlterField(
            model_name='itemcatalogoapu',
            name='precio_base',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Precio/salario base del ítem por unidad ($/und, $/día, $/mes…).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='itemcatalogoapu',
            name='unidad',
            field=models.CharField(choices=[('dia', 'Día'), ('mes', 'Mes'), ('hora', 'Hora'), ('und', 'Unidad'), ('mts', 'Metros'), ('global', 'Global')], default='und', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemcatalogoapu',
            name='vida_util_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Vida útil en días. Permite calcular costo por jornada.', null=True),
        ),
        migrations.CreateModel(
            name='APUProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre del APU, p. ej. 'APU Cubierta TPO — Edificio Central'.", max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del alcance y condiciones del APU.')),
                ('factor_venta_pct', models.DecimalField(decimal_places=4, default=Decimal('20'), help_text='% margen sobre costo unitario → valor unitario.', max_digits=8)),
                ('iva_pct', models.DecimalField(decimal_places=4, default=Decimal('19'), max_digits=8)),
                ('aplica_iva', models.BooleanField(default=True)),
                ('subtotal_materiales', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Suma de costo_total de todas las líneas de MATERIALES.', max_digits=18)),
                ('subtotal_herramientas', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Suma de costo_total de todas las líneas de HERRAMIENTAS_EQUIPOS.', max_digits=18)),
                ('subtotal_transporte', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('subtotal_mano_obra', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('subtotal_administracion', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('total_costo', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Suma de todos los costo_total (sin margen de venta).', max_digits=18)),
                ('total_valor_venta', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Suma de todos los valor_total (con margen de venta).', max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto_sistema', models.OneToOneField(blank=True, help_text='ProyectoSistema al que pertenece este APU (si aplica).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apu', to='presupuestos.proyectosistema')),
            ],
            options={
                'verbose_name': 'APU',
                'verbose_name_plural': 'APUs',
                'db_table': 'apus',
            },
        ),
        migrations.AlterField(
            model_name='apulinea',
            name='apu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='presupuestos.apuproyecto'),
        ),
        migrations.DeleteModel(
            name='APU',
        ),
    ]
