# Generated by Django 4.2.29 on 2026-04-06 14:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_alter_apulinea_costo_por_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuproyecto',
            name='factor_venta_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('121'), help_text='Factor de venta: Valor unit = Costo total × (factor/100). Ej: 121 → × 1.21.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='configuracionapu',
            name='factor_venta_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('121'), help_text='Factor de venta aplicado al costo total para obtener el valor unitario. Ej: 121 → multiplica × 1.21.', max_digits=8),
        ),
    ]
