# Generated by Django 4.2.29 on 2026-04-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0006_tienda_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apulinea',
            name='costo_por_dia',
        ),
    ]
