# Generated by Django 4.2.29 on 2026-04-06 16:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0007_remove_apulinea_costo_por_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='apulinea',
            name='costo_por_dia',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Precio_referencia / vida_util_dias. Calculado automáticamente.', max_digits=18),
        ),
    ]
