# Generated by Django 4.2.29 on 2026-04-06 21:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0009_apuproyecto_aiu_margen_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuproyecto',
            name='aiu_contratista_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('30'), help_text='AIU del contratista (%). Se aplica al calcular costo unitario de MO, herramientas, transporte y admin.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='apuproyecto',
            name='dias_duracion',
            field=models.PositiveIntegerField(default=30, help_text='Días de duración del proyecto. Se usa para calcular el costo unitario de MO, herramientas, etc.'),
        ),
        migrations.AlterField(
            model_name='apuproyecto',
            name='factor_venta_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('121'), help_text='Factor de venta: Valor unit = Costo unit × (factor/100). Ej: 121 → × 1.21.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='apuproyecto',
            name='margen_ganancia_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('20'), help_text='Margen de ganancia (%). Se aplica junto al AIU en el costo unitario.', max_digits=8),
        ),
    ]
