# Generated by Django 4.2.29 on 2026-04-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0010_alter_apuproyecto_aiu_contratista_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaitemapu',
            name='formula_costo_item',
            field=models.TextField(blank=True, default='', help_text='Expresión Python que calcula el COSTO DE UN ÍTEM para toda la duración del proyecto. El servicio multiplica el resultado por la cantidad y luego divide por tp (total unidades base).<br><b>Variables disponibles:</b><br>· <code>precio_base</code> — precio base del ítem<br>· <code>salario_base</code>, <code>prestaciones</code> — para personal<br>· <code>precio_mes</code> — salario_base + prestaciones<br>· <code>vida_util_dias</code> — vida útil en días (herramientas; 1 si no aplica)<br>· <code>dias_duracion</code> — días de duración del proyecto<br>· <code>aiu</code> — factor AIU (ej: 1.30 si AIU=30%)<br>· <code>margen</code> — factor margen (ej: 1.20 si margen=20%)<br>· <code>num_personas</code> — total personas en cuadrilla<br>· <code>tiempo</code> — dias_duracion / 30 (fracción del mes)<br><b>Ejemplos:</b><br>Personal MO: <code>precio_mes * aiu * margen * tiempo</code><br>Dotación: <code>precio_base * num_personas * aiu * margen</code><br>Herramienta: <code>(precio_base / vida_util_dias) * dias_duracion * aiu * margen if vida_util_dias > 0 else precio_base * aiu * margen</code><br>Transporte o Admin: <code>precio_base</code>', verbose_name='Fórmula de costo del ítem'),
        ),
    ]
