# Generated by Django 4.2.29 on 2026-04-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0011_add_formula_costo_item_a_categoria_apu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaitemapu',
            name='formula_costo_item',
        ),
    ]
