# Generated by Django 4.2.29 on 2026-04-08 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0004_componente_apu_campos'),
        ('presupuestos', '0012_remove_categoriaitemapu_formula_costo_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaitemapu',
            name='aplica_dias_mensuales',
            field=models.BooleanField(default=False, help_text='Si True, los días de duración se dividen entre 30 en la fórmula de costo. Usar en categorías de personal donde el salario es mensual.'),
        ),
        migrations.CreateModel(
            name='ReglaAPUSubsistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_apu', models.CharField(choices=[('HERRAMIENTAS_EQUIPOS', 'Herramientas y equipos'), ('TRANSPORTE', 'Transporte'), ('MANO_DE_OBRA', 'Mano de obra'), ('ADMINISTRACION', 'Administración')], help_text='Tipo de APU al que aplica esta regla (no aplica a MATERIALES).', max_length=30)),
                ('formula_costo_unitario', models.TextField(help_text='Expresión Python que devuelve el costo unitario de la categoría. Variables: suma, aiu, margen, dias, tp, personas, factor_venta. Ej (herramientas): suma * aiu * margen * dias / tp')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_apu', to='ingenieria.subsistema')),
            ],
            options={
                'verbose_name': 'Regla APU de subsistema',
                'verbose_name_plural': 'Reglas APU de subsistema',
                'db_table': 'reglas_apu_subsistema',
                'ordering': ['subsistema', 'orden'],
                'unique_together': {('subsistema', 'tipo_apu')},
            },
        ),
    ]
