# Generated by Django 4.2.29 on 2026-04-09 14:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0013_regla_apu_subsistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuproyecto',
            name='factor_venta_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('20'), help_text='Margen de venta (%). Valor unit = Costo unit × (1 + factor/100). Ej: 20 → × 1.20.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='configuracionapu',
            name='factor_venta_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('20'), help_text='Margen de venta (%). Se suma al costo para obtener el valor unitario. Ej: 20 → multiplica × 1.20.', max_digits=8),
        ),
    ]
