# Generated by Django 4.2.29 on 2026-04-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0015_update_state_configuracionsistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apulinea',
            name='editable',
            field=models.BooleanField(default=False, help_text='Si True, la configuracion puede modificar precio_referencia y rendimiento.'),
        ),
    ]
