# Generated by Django 4.2.29 on 2026-04-10 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0005_alter_dependenciatecnica_table_and_more'),
        ('presupuestos', '0016_alter_apulinea_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectosistema',
            name='subsistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyecto_sistemas', to='ingenieria.subsistema'),
        ),
    ]
