# Generated by Django 4.2.29 on 2026-04-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0018_calculo_consumo_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculoconsumolinea',
            name='capa_nombre',
            field=models.CharField(help_text="Nombre de la capa o componente. Ej: 'Impermeabilizante', 'Comp. A (Base)'", max_length=200),
        ),
    ]
