# Generated by Django 4.2.29 on 2026-05-08 21:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0019_alter_calculoconsumolinea_capa_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuproyecto',
            name='aiu_proyecto_admin_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('10'), help_text='Administración del proyecto (%). Se aplica sobre los costos directos para la modalidad AIU del proyecto.', max_digits=8),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='aiu_proyecto_imprevistos_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('5'), help_text='Imprevistos del proyecto (%).', max_digits=8),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='aiu_proyecto_utilidad_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('8'), help_text='Utilidad del proyecto (%).', max_digits=8),
        ),
    ]
