# Generated by Django 4.2.29 on 2026-05-12 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_unidadalianza_imagen'),
        ('presupuestos', '0020_apuproyecto_aiu_proyecto_admin_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuproyecto',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apus_aprobados', to='configuracion.configuracionsistema', verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='fecha_envio_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío a revisión'),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='modalidad_aiu_seleccionada',
            field=models.CharField(blank=True, choices=[('1', 'Modalidad 1 — AIU sobre todos los costos directos'), ('2', 'Modalidad 2 — AIU sobre costos directos sin materiales')], max_length=2, null=True, verbose_name='Modalidad AIU seleccionada'),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apus_en_revision', to='configuracion.configuracionsistema', verbose_name='Revisor asignado'),
        ),
    ]
