# Generated by Django 4.2.29 on 2026-06-10 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0018_despiecemaestrolinea_valores_usados_and_more'),
        ('presupuestos', '0021_apuproyecto_revision_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsistemaItemAPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HERRAMIENTAS_EQUIPOS', 'Herramientas y equipos'), ('TRANSPORTE', 'Transporte'), ('MANO_DE_OBRA', 'Mano de obra'), ('ADMINISTRACION', 'Administración')], help_text='Tipo de APU bajo el cual aplica el ítem. Debe coincidir con categoria.tipo_apu del item_catalogo en flujos normales.', max_length=30)),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad predeterminada del ítem para este subsistema.')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de presentación dentro de la categoría.')),
                ('activo', models.BooleanField(default=True, help_text='Si False, el ítem se ignora al generar el APU.')),
                ('rendimiento_override', models.DecimalField(blank=True, decimal_places=6, help_text='Rendimiento explícito para sobrescribir el cálculo por fórmula. Si es NULL, se respeta el cálculo estándar de APUService.', max_digits=14, null=True)),
                ('observaciones', models.TextField(blank=True, default='', help_text='Notas internas sobre por qué este ítem aplica al subsistema.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_catalogo', models.ForeignKey(help_text='Ítem del catálogo APU asociado al subsistema.', on_delete=django.db.models.deletion.CASCADE, related_name='asociaciones_subsistema', to='presupuestos.itemcatalogoapu')),
                ('subsistema', models.ForeignKey(help_text='Subsistema al que aplica este ítem APU predeterminado.', on_delete=django.db.models.deletion.CASCADE, related_name='items_apu', to='ingenieria.subsistema')),
            ],
            options={
                'verbose_name': 'Ítem APU del subsistema',
                'verbose_name_plural': 'Ítems APU del subsistema',
                'db_table': 'subsistema_items_apu',
                'ordering': ['subsistema', 'tipo', 'orden', 'item_catalogo__nombre'],
                'unique_together': {('subsistema', 'item_catalogo', 'tipo')},
            },
        ),
    ]
