# Generated by Django 4.2.29 on 2026-06-11 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0018_tipogarantia'),
        ('presupuestos', '0022_subsistema_item_apu'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuproyecto',
            name='aplica_garantia',
            field=models.BooleanField(default=False, help_text='Indica si la propuesta incluye garantía. No afecta el cálculo.'),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='tipo_garantia',
            field=models.ForeignKey(blank=True, help_text='Tipo de garantía ofrecida en la propuesta (opcional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apus', to='comercial.tipogarantia'),
        ),
    ]
