# Generated by Django 4.2.29 on 2026-06-12 16:42

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0023_apuproyecto_aplica_garantia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuproyecto',
            name='garantia_base_valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Base sobre la que se calculó el recargo.', max_digits=14),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='garantia_material_linea',
            field=models.ForeignKey(blank=True, help_text='APULinea tipo Materiales sobre la que se aplica el recargo (modo MATERIAL_ESPECIFICO).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='presupuestos.apulinea'),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='garantia_material_nombre_snapshot',
            field=models.CharField(blank=True, default='', help_text='Snapshot textual del material objetivo (para trazabilidad si la línea se elimina).', max_length=255),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='garantia_modo_aplicacion',
            field=models.CharField(blank=True, choices=[('TOTAL_MATERIALES', 'Sobre el total de materiales'), ('MATERIAL_ESPECIFICO', 'Sobre un material específico')], default='', help_text='Cómo se aplica la garantía: sobre el total de materiales o sobre un material específico.', max_length=24),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='garantia_porcentaje_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot del % de recargo tomado del catálogo al armar/editar la garantía.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='garantia_valor_recargo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Recargo comercial sumado a total_valor_venta.', max_digits=14),
        ),
    ]
