# Generated by Django 4.2.29 on 2026-06-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0024_apuproyecto_garantia_base_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuproyecto',
            name='aiu_final_admin_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Snapshot de Administración (%) aprobado por el revisor. Si NULL usa aiu_proyecto_admin_pct.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='aiu_final_imprevistos_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Snapshot de Imprevistos (%) aprobado por el revisor. Si NULL usa aiu_proyecto_imprevistos_pct.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='aiu_final_utilidad_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Snapshot de Utilidad (%) aprobado por el revisor. Si NULL usa aiu_proyecto_utilidad_pct.', max_digits=8, null=True),
        ),
    ]
