# Generated by Django 4.2.29 on 2026-06-16 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0018_despiecemaestrolinea_valores_usados_and_more'),
        ('presupuestos', '0025_apuproyecto_aiu_final_admin_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apulinea',
            name='despiece_maestro',
            field=models.ForeignKey(blank=True, help_text='DespieceMaestro de origen (sólo MATERIALES). NULL en líneas legacy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apu_lineas', to='ingenieria.despiecemaestro'),
        ),
        migrations.AddField(
            model_name='apulinea',
            name='sistema_nombre_snapshot',
            field=models.CharField(blank=True, default='', help_text='Snapshot textual del sistema asociado a la línea (Fase 11.4).', max_length=120),
        ),
        migrations.AddField(
            model_name='apulinea',
            name='subsistema_nombre_snapshot',
            field=models.CharField(blank=True, default='', help_text='Snapshot textual del subsistema asociado a la línea (Fase 11.4).', max_length=120),
        ),
        migrations.CreateModel(
            name='APUDespieceIncluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema_nombre_snapshot', models.CharField(blank=True, default='', help_text='Snapshot textual del sistema en el momento de la inclusión.', max_length=120)),
                ('subsistema_nombre_snapshot', models.CharField(blank=True, default='', help_text='Snapshot textual del subsistema en el momento de la inclusión.', max_length=120)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de presentación dentro del APU.')),
                ('activo', models.BooleanField(default=True, help_text='Si False, no se considera incluido (no se borra para preservar histórico).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apu', models.ForeignKey(help_text='APU al que pertenece este despiece.', on_delete=django.db.models.deletion.CASCADE, related_name='despieces_incluidos', to='presupuestos.apuproyecto')),
                ('despiece_maestro', models.ForeignKey(help_text='DespieceMaestro seleccionado para el APU.', on_delete=django.db.models.deletion.PROTECT, related_name='apus_incluidos', to='ingenieria.despiecemaestro')),
            ],
            options={
                'verbose_name': 'Despiece incluido en APU',
                'verbose_name_plural': 'Despieces incluidos en APU',
                'db_table': 'apu_despieces_incluidos',
                'ordering': ['apu', 'orden', 'id'],
                'unique_together': {('apu', 'despiece_maestro')},
            },
        ),
    ]
