# Generated by Django 4.2.29 on 2026-06-16 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0019_tipogarantia_porcentaje_recargo_and_more'),
        ('presupuestos', '0026_apulinea_despiece_maestro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apulinea',
            name='apu_origen',
            field=models.ForeignKey(blank=True, help_text='APU individual de origen (sólo en APUs consolidados, Fase 11.5).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_consolidadas', to='presupuestos.apuproyecto'),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto contenedor. Sólo se usa en APUs consolidados; los individuales lo derivan de proyecto_sistema.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apus_consolidados', to='comercial.proyecto'),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='tipo_apu',
            field=models.CharField(choices=[('INDIVIDUAL', 'APU individual'), ('CONSOLIDADO', 'APU consolidado')], db_index=True, default='INDIVIDUAL', help_text='INDIVIDUAL (flujo histórico) o CONSOLIDADO (unión opcional de varios APUs).', max_length=20),
        ),
        migrations.CreateModel(
            name='APUConsolidadoOrigen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('incluido_en_pdf_cliente', models.BooleanField(default=True, help_text='Si False, este origen no se lista en el PDF Cliente del consolidado.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apu_consolidado', models.ForeignKey(help_text='APU consolidado contenedor.', on_delete=django.db.models.deletion.CASCADE, related_name='origenes_consolidado', to='presupuestos.apuproyecto')),
                ('apu_origen', models.ForeignKey(help_text='APU individual de origen.', on_delete=django.db.models.deletion.PROTECT, related_name='consolidaciones_destino', to='presupuestos.apuproyecto')),
            ],
            options={
                'verbose_name': 'Origen de APU consolidado',
                'verbose_name_plural': 'Orígenes de APUs consolidados',
                'db_table': 'apu_consolidado_origenes',
                'ordering': ['apu_consolidado', 'orden', 'id'],
                'unique_together': {('apu_consolidado', 'apu_origen')},
            },
        ),
    ]
