# Generated by Django 4.2.29 on 2026-06-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_unidadalianza_imagen'),
        ('presupuestos', '0027_apulinea_apu_origen_apuproyecto_proyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuproyecto',
            name='archivado',
            field=models.BooleanField(db_index=True, default=False, help_text='Si True, el APU está archivado: oculto en listas por defecto, preserva trazabilidad.'),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='archivado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apus_archivados', to='configuracion.configuracionsistema'),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='fecha_archivado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='motivo_archivado',
            field=models.TextField(blank=True, default=''),
        ),
    ]
