# Generated by Django 4.2.29 on 2026-06-17 17:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0020_solicitud_motivo_devolucion_alter_solicitud_estado'),
        ('configuracion', '0009_unidadalianza_imagen'),
        ('presupuestos', '0028_apuproyecto_archivado_apuproyecto_archivado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionAPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apu_nombre_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('tipo_apu_snapshot', models.CharField(blank=True, default='', help_text='INDIVIDUAL o CONSOLIDADO al momento de la aprobación.', max_length=20)),
                ('proyecto_nombre_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('proyecto_consecutivo_snapshot', models.CharField(blank=True, default='', max_length=30)),
                ('solicitud_consecutivo_snapshot', models.CharField(blank=True, default='', max_length=30)),
                ('cliente_nombre_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('cliente_nit_snapshot', models.CharField(blank=True, default='', max_length=50)),
                ('moneda_snapshot', models.CharField(blank=True, default='COP', max_length=10)),
                ('modalidad_aiu_snapshot', models.CharField(blank=True, default='', help_text="'1' o '2' — modalidad aprobada al momento del snapshot.", max_length=2)),
                ('aprobado_por_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('fecha_aprobacion_snapshot', models.DateTimeField(blank=True, null=True)),
                ('subtotal_materiales', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('subtotal_herramientas', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('subtotal_transporte', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('subtotal_mano_obra', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('subtotal_administracion', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('subtotal_directos_tecnico', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('aiu_admin_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('aiu_imprevistos_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('aiu_utilidad_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('aiu_admin_valor', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('aiu_imprevistos_valor', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('aiu_utilidad_valor', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('total_aiu', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('garantia_aplica', models.BooleanField(default=False)),
                ('garantia_nombre_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('garantia_porcentaje_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('garantia_modo_snapshot', models.CharField(blank=True, default='', max_length=24)),
                ('garantia_material_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('garantia_base_valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('garantia_valor_recargo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('aplica_iva', models.BooleanField(default=True)),
                ('iva_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('iva_base', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('iva_valor', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('iva_label', models.CharField(blank=True, default='', max_length=120)),
                ('total_final', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('version', models.PositiveIntegerField(db_index=True, default=1, help_text='Versión por APU. La última con estado=APROBADA es la vigente.')),
                ('estado', models.CharField(choices=[('APROBADA', 'Aprobada (vigente)'), ('REEMPLAZADA', 'Reemplazada')], db_index=True, default='APROBADA', max_length=20)),
                ('data_snapshot', models.JSONField(blank=True, default=dict, help_text='JSON con líneas, secciones comerciales, despieces incluidos, APUs origen, resumen de consolidación, observaciones.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_aprobadas', to='configuracion.configuracionsistema')),
                ('apu', models.ForeignKey(help_text='APU del que proviene el snapshot. PROTECT — un APU con cotización aprobada debe archivarse, no eliminarse.', on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='presupuestos.apuproyecto')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_aprobadas', to='comercial.cliente')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_aprobadas', to='comercial.proyecto')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_aprobadas', to='comercial.solicitud')),
            ],
            options={
                'verbose_name': 'Cotización APU aprobada',
                'verbose_name_plural': 'Cotizaciones APU aprobadas',
                'db_table': 'cotizaciones_apu',
                'ordering': ['-apu_id', '-version'],
                'unique_together': {('apu', 'version')},
            },
        ),
    ]
