# Generated by Django 4.2.29 on 2026-07-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0029_cotizacionapu'),
    ]

    operations = [
        migrations.AddField(
            model_name='despiecelinea',
            name='pendiente_producto',
            field=models.BooleanField(default=False, help_text='True cuando el componente tiene requiere_presentacion_producto=True y aún no se ha seleccionado el producto. En este estado cantidad_calculada es None.'),
        ),
        migrations.AddField(
            model_name='despiecelinea',
            name='presentacion_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valor de Producto.cantidad_presentacion usado en el último cálculo. Se guarda para trazabilidad aunque el producto cambie después.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='despiecelinea',
            name='cantidad_calculada',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Cantidad calculada por la fórmula. None cuando el componente requiere selección de producto para calcular (ver pendiente_producto).', max_digits=18, null=True),
        ),
    ]
