# Generated by Django 4.2.29 on 2026-08-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0030_despiecelinea_pendiente_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuproyecto',
            name='apus_presupuesto_ids',
            field=models.JSONField(blank=True, default=list, help_text='Lista de PKs de otros APUProyecto del mismo proyecto que se incluyen en el cálculo del presupuesto final consolidado. Se guarda al enviar a revisión.'),
        ),
    ]
