# Generated by Django 4.2.29 on 2026-08-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0031_apuproyecto_apus_presupuesto_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apuproyecto',
            name='aplica_garantia',
        ),
        migrations.RemoveField(
            model_name='apuproyecto',
            name='garantia_base_valor',
        ),
        migrations.RemoveField(
            model_name='apuproyecto',
            name='garantia_material_linea',
        ),
        migrations.RemoveField(
            model_name='apuproyecto',
            name='garantia_material_nombre_snapshot',
        ),
        migrations.RemoveField(
            model_name='apuproyecto',
            name='garantia_modo_aplicacion',
        ),
        migrations.RemoveField(
            model_name='apuproyecto',
            name='garantia_porcentaje_aplicado',
        ),
        migrations.RemoveField(
            model_name='apuproyecto',
            name='garantia_valor_recargo',
        ),
        migrations.RemoveField(
            model_name='apuproyecto',
            name='tipo_garantia',
        ),
        migrations.RemoveField(
            model_name='cotizacionapu',
            name='garantia_aplica',
        ),
        migrations.RemoveField(
            model_name='cotizacionapu',
            name='garantia_base_valor',
        ),
        migrations.RemoveField(
            model_name='cotizacionapu',
            name='garantia_material_snapshot',
        ),
        migrations.RemoveField(
            model_name='cotizacionapu',
            name='garantia_modo_snapshot',
        ),
        migrations.RemoveField(
            model_name='cotizacionapu',
            name='garantia_nombre_snapshot',
        ),
        migrations.RemoveField(
            model_name='cotizacionapu',
            name='garantia_porcentaje_snapshot',
        ),
        migrations.RemoveField(
            model_name='cotizacionapu',
            name='garantia_valor_recargo',
        ),
    ]
