# Generated by Django 4.2.29 on 2026-08-12 16:46

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0032_eliminar_garantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuproyecto',
            name='subtotal_polizas',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Suma de valor_calculado de las pólizas activas del APU. Calculado automáticamente.', max_digits=18),
        ),
        migrations.CreateModel(
            name='APUPoliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la póliza')),
                ('porcentaje', models.DecimalField(decimal_places=4, help_text='Porcentaje sobre la base seleccionada. Ej: 1.5 → 1.5 %.', max_digits=8, verbose_name='Porcentaje (%)')),
                ('base_calculo', models.CharField(choices=[('total_directo', 'Total costos directos (mat + herr + transp + MO)'), ('mano_obra', 'Mano de obra'), ('materiales', 'Materiales'), ('transporte', 'Transporte'), ('herramientas', 'Herramientas y equipos')], default='total_directo', max_length=40, verbose_name='Base de cálculo')),
                ('base_calculada', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Valor de la base en el último recálculo. Actualizado automáticamente.', max_digits=18)),
                ('valor_calculado', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='base_calculada × porcentaje / 100. Actualizado automáticamente.', max_digits=18)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='presupuestos.apuproyecto')),
            ],
            options={
                'verbose_name': 'Póliza APU',
                'verbose_name_plural': 'Pólizas APU',
                'db_table': 'apu_polizas',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
