# Generated by Django 4.2.29 on 2026-08-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0033_apupoliza'),
    ]

    operations = [
        migrations.AddField(
            model_name='apupoliza',
            name='bases_calculo',
            field=models.JSONField(blank=True, default=list, help_text="Lista de bases seleccionadas. Ej: ['materiales', 'mano_obra']. Si está vacía, se usa base_calculo (compatibilidad). Valores válidos: total_directo, mano_obra, materiales, transporte, herramientas.", verbose_name='Bases de cálculo'),
        ),
        migrations.AlterField(
            model_name='apupoliza',
            name='base_calculo',
            field=models.CharField(choices=[('total_directo', 'Total costos directos (mat + herr + transp + MO)'), ('mano_obra', 'Mano de obra'), ('materiales', 'Materiales'), ('transporte', 'Transporte'), ('herramientas', 'Herramientas y equipos')], default='total_directo', help_text='Campo heredado. Usar bases_calculo para selección múltiple.', max_length=40, verbose_name='Base de cálculo (legacy, una sola)'),
        ),
    ]
