# Generated by Django 4.2.29 on 2026-09-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0036_apuproyecto_valor_materiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='despiecelinea',
            name='cantidad_redondeada',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Cantidad comercial redondeada arrastrada desde el despiece (DespieceMaestroLinea.cantidad_redondeada / ConsolidacionDespieceMaestro.cantidad_redondeada). Es la que usa el APU para valorizar materiales. Si es None, el APU cae a math.ceil(cantidad_final).', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='apuproyecto',
            name='cantidad_base_apu',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad de referencia del APU (p. ej. m², ml). Se calcula automáticamente al ejecutar «Guardar APU» desde el panel confirmado. valor_total_proyecto = cantidad_base_apu × total_valor_venta.', max_digits=18, null=True),
        ),
    ]
