# Generated by Django 4.2.29 on 2026-09-09 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0012_trmvigente'),
        ('presupuestos', '0037_despiecelinea_cantidad_redondeada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuproyecto',
            name='enviado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que remitió el APU a revisión. Se usa para la segregación de funciones: quien envía no puede autorizar su propio envío.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apus_enviados', to='configuracion.configuracionsistema', verbose_name='Enviado a revisión por'),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='fecha_reasignacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reasignación del revisor'),
        ),
        migrations.AddField(
            model_name='apuproyecto',
            name='reasignado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que cambió el revisor asignado, si hubo reasignación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apus_reasignados', to='configuracion.configuracionsistema', verbose_name='Revisor reasignado por'),
        ),
    ]
