# Generated by Django 4.2.29 on 2026-03-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosistema',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('PRESUPUESTOS', 'Presupuestos'), ('COMPRAS', 'Compras'), ('ASESOR_COMERCIAL', 'Asesor comercial'), ('SOLO_LECTURA', 'Solo lectura')], default='SOLO_LECTURA', help_text='Rol del usuario en el sistema', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='unidad_negocio',
            field=models.CharField(choices=[('IMPERANDINA', 'Imperandina'), ('SOLARANDINA', 'Solarandina'), ('IMPERTIENDA', 'Impertienda')], help_text='Unidad de negocio a la que pertenece el usuario', max_length=20),
        ),
    ]
