# Generated by Django 4.2.29 on 2026-04-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_rename_usuariosistema_to_configuracionsistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('PRESUPUESTOS', 'Presupuestos'), ('COMPRAS', 'Compras'), ('ASESOR_COMERCIAL', 'Asesor comercial'), ('SOLO_LECTURA', 'Solo lectura')], default='SOLO_LECTURA', help_text='Rol de la configuración en el sistema', max_length=30),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='unidad_negocio',
            field=models.CharField(choices=[('IMPERANDINA', 'Imperandina'), ('SOLARANDINA', 'Solarandina'), ('IMPERTIENDA', 'Impertienda')], help_text='Unidad de negocio a la que pertenece la configuración', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidadnegocioinfo',
            name='codigo',
            field=models.CharField(choices=[('IMPERANDINA', 'Imperandina'), ('SOLARANDINA', 'Solarandina'), ('IMPERTIENDA', 'Impertienda')], help_text='Identificador de la unidad de negocio.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='unidadnegocioinfo',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción / notas'),
        ),
        migrations.AlterField(
            model_name='unidadnegocioinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unidadnegocioinfo',
            name='nit',
            field=models.CharField(blank=True, max_length=30, verbose_name='NIT'),
        ),
    ]
