# Generated by Django 4.2.29 on 2026-04-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_unidad_secciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadalianza',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unidadclausula',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unidadnegocioinfo',
            name='quienes_somos',
            field=models.TextField(blank=True, default='', help_text='Texto de presentación de la unidad de negocio.', verbose_name='Quiénes somos'),
        ),
        migrations.AlterField(
            model_name='unidadpolitica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
