# Generated by Django 4.2.29 on 2026-06-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_unidadalianza_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('GERENTE', 'Gerente'), ('PRESUPUESTOS', 'Presupuestos'), ('ASESOR_COMERCIAL', 'Asesor comercial'), ('COMPRAS', 'Compras'), ('SOLO_LECTURA', 'Solo lectura')], default='SOLO_LECTURA', help_text='Rol de la configuración en el sistema', max_length=30),
        ),
    ]
