# Generated by Django 4.2.29 on 2026-06-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0010_alter_configuracionsistema_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='unidad_negocio',
            field=models.CharField(choices=[('IMPERANDINA', 'Imperandina'), ('SOLARANDINA', 'Solarandina'), ('IMPERTIENDA', 'Impertienda'), ('EDILANDINA', 'Edilandina')], help_text='Unidad de negocio a la que pertenece la configuración', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidadnegocioinfo',
            name='codigo',
            field=models.CharField(choices=[('IMPERANDINA', 'Imperandina'), ('SOLARANDINA', 'Solarandina'), ('IMPERTIENDA', 'Impertienda'), ('EDILANDINA', 'Edilandina')], help_text='Identificador de la unidad de negocio.', max_length=20, unique=True),
        ),
    ]
