# Generated by Django 4.2.29 on 2026-08-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0011_alter_configuracionsistema_unidad_negocio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRMVigente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, help_text='Valor de la TRM en COP/USD.', max_digits=14)),
                ('fecha', models.DateField(help_text='Fecha oficial de vigencia de esta TRM (publicada por SuperFinanciera).')),
                ('fuente', models.CharField(default='Superintendencia Financiera de Colombia', max_length=120)),
                ('vigente', models.BooleanField(db_index=True, default=True, help_text='True → es la TRM actualmente activa. Solo uno por vez.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TRM vigente',
                'verbose_name_plural': 'Historial de TRM',
                'db_table': 'configuracion_trm_vigente',
                'ordering': ['-fecha', '-created_at'],
                'get_latest_by': 'fecha',
            },
        ),
    ]
