# Generated by Django 4.2.29 on 2026-03-20 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('linea_negocio', models.CharField(choices=[('CUBIERTAS', 'Cubiertas'), ('FACHADAS', 'Fachadas'), ('OTROS', 'Otros')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
                'db_table': 'sistemas',
            },
        ),
        migrations.CreateModel(
            name='Subsistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sistema', models.ForeignKey(help_text='Sistema padre al que pertenece esta variante técnica', on_delete=django.db.models.deletion.CASCADE, related_name='subsistemas', to='ingenieria.sistema')),
            ],
            options={
                'verbose_name': 'Subsistema (Receta Técnica)',
                'verbose_name_plural': 'Subsistemas (Recetas)',
                'db_table': 'subsistemas',
                'unique_together': {('sistema', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='DependenciaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre descriptivo', max_length=200)),
                ('obligatoria', models.BooleanField(default=True, help_text='Si es False, el comercial puede quitar este ítem en el presupuesto.')),
                ('orden', models.IntegerField(default=1, help_text='Secuencia de aparición en el listado de materiales.')),
                ('variable_entrada', models.CharField(blank=True, max_length=80, null=True)),
                ('condicion_texto', models.TextField(blank=True, null=True)),
                ('tipo_regla', models.CharField(choices=[('FIJA', 'Fija'), ('VARIABLE_SISTEMA', 'Variable sistema'), ('VARIABLE_PROYECTO', 'Variable proyecto'), ('EDITABLE_USUARIO', 'Editable usuario'), ('DERIVADA', 'Derivada de otro producto')], default='FIJA', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria_producto', models.ForeignKey(blank=True, help_text='Categoría cuando el producto se elegirá por proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencias_tecnicas', to='catalogos.categoriaproducto')),
                ('producto_dependiente', models.ForeignKey(blank=True, help_text='EXCEPCIÓN: Solo si el componente es un SKU específico e inamovible.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencias_dependiente', to='catalogos.producto')),
                ('producto_origen', models.ForeignKey(blank=True, help_text='Si es NULL, el componente se añade siempre que se use el subsistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencias_origen', to='catalogos.producto')),
                ('subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias', to='ingenieria.subsistema')),
            ],
            options={
                'verbose_name': 'Dependencia de Componente',
                'verbose_name_plural': 'Dependencias de Componentes',
                'db_table': 'dependencias_tecnicas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ReglaCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=200)),
                ('variable_entrada', models.CharField(blank=True, help_text='Nombre de la variable de contexto usada como base (ej: Total_PowerGrip)', max_length=80, null=True)),
                ('coeficiente', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('divisor', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('factor_desperdicio', models.DecimalField(decimal_places=6, default=1.01, max_digits=12)),
                ('formula_texto', models.TextField(help_text='Expresión legible. Ej: (8 × Total_PowerGrip) * 101%')),
                ('formula_python', models.TextField(blank=True, help_text='Expresión Python evaluable. Usa variables del contexto.', null=True)),
                ('tipo_regla', models.CharField(choices=[('FIJA', 'Fija'), ('VARIABLE_SISTEMA', 'Variable sistema'), ('VARIABLE_PROYECTO', 'Variable proyecto'), ('EDITABLE_USUARIO', 'Editable usuario'), ('DERIVADA', 'Derivada de otro producto')], default='FIJA', max_length=30)),
                ('orden_ejecucion', models.IntegerField(default=1)),
                ('editable_por_proyecto', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
                ('obligatoria', models.BooleanField(default=True, help_text='Si es False, el componente puede omitirse en el despiece de un proyecto')),
                ('variable_salida', models.CharField(blank=True, help_text="Nombre con el que el resultado de esta regla queda disponible en el contexto para reglas derivadas. Ej: 'Limpiador' → permite que Estopa use formula_python='Limpiador / 2'", max_length=80)),
                ('caso_prueba', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria_producto', models.ForeignKey(blank=True, help_text='Categoría del producto cuando no hay producto específico asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_calculo', to='catalogos.categoriaproducto')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_creadas', to='usuarios.usuariosistema')),
                ('producto', models.ForeignKey(blank=True, help_text='Producto específico (opcional; use categoría si el producto se elige por proyecto)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_calculo', to='catalogos.producto')),
                ('subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='ingenieria.subsistema')),
            ],
            options={
                'verbose_name': 'Regla de Cálculo',
                'verbose_name_plural': 'Reglas de Cálculo',
                'db_table': 'reglas_calculo',
                'ordering': ['orden_ejecucion'],
                'unique_together': {('subsistema', 'codigo', 'version')},
            },
        ),
    ]
