# Generated by Django 4.2.29 on 2026-03-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('ingenieria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependenciatecnica',
            name='categoria_producto',
            field=models.ForeignKey(blank=True, help_text='Categoría cuando el producto se elegirá por proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencias_tecnicas', to='catalogos.categoriaproducto'),
        ),
        migrations.AlterField(
            model_name='dependenciatecnica',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre descriptivo (obligatorio para dependencias basadas en categoría)', max_length=200),
        ),
        migrations.AlterField(
            model_name='dependenciatecnica',
            name='producto_dependiente',
            field=models.ForeignKey(blank=True, help_text='Producto concreto (opcional; use categoría para dependencias genéricas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencias_dependiente', to='catalogos.producto'),
        ),
        migrations.AlterField(
            model_name='dependenciatecnica',
            name='producto_origen',
            field=models.ForeignKey(blank=True, help_text='Si es NULL la dependencia aplica a todo el subsistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencias_origen', to='catalogos.producto'),
        ),
        migrations.AlterField(
            model_name='reglacalculo',
            name='categoria_producto',
            field=models.ForeignKey(blank=True, help_text='Categoría del producto cuando no hay producto específico asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_calculo', to='catalogos.categoriaproducto'),
        ),
        migrations.AlterField(
            model_name='reglacalculo',
            name='formula_python',
            field=models.TextField(blank=True, help_text='Expresión Python evaluable. Usa variables del contexto.', null=True),
        ),
        migrations.AlterField(
            model_name='reglacalculo',
            name='formula_texto',
            field=models.TextField(help_text='Expresión legible. Ej: (8 × Total_PowerGrip) * 101%'),
        ),
        migrations.AlterField(
            model_name='reglacalculo',
            name='obligatoria',
            field=models.BooleanField(default=True, help_text='Si es False, el componente puede omitirse en el despiece de un proyecto'),
        ),
        migrations.AlterField(
            model_name='reglacalculo',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto específico (opcional; use categoría si el producto se elige por proyecto)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_calculo', to='catalogos.producto'),
        ),
        migrations.AlterField(
            model_name='reglacalculo',
            name='variable_entrada',
            field=models.CharField(blank=True, help_text='Nombre de la variable de contexto usada como base (ej: Total_PowerGrip)', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='reglacalculo',
            name='variable_salida',
            field=models.CharField(blank=True, help_text="Nombre con el que el resultado de esta regla queda disponible en el contexto para reglas derivadas. Ej: 'Limpiador' → permite que Estopa use formula_python='Limpiador / 2'", max_length=80),
        ),
    ]
