# Generated by Django 4.2.29 on 2026-03-31 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_producto_ficha_tecnica'),
        ('ingenieria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableSubsistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(help_text='Nombre interno de la variable, sin espacios. Ej: total_powergrip', max_length=80)),
                ('label', models.CharField(help_text='Etiqueta legible para el usuario', max_length=200)),
                ('unidad', models.CharField(blank=True, default='', max_length=40)),
                ('valor_default', models.DecimalField(decimal_places=6, default=0, help_text='Valor por defecto si el usuario no lo modifica', max_digits=18)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables_db', to='ingenieria.subsistema')),
            ],
            options={
                'verbose_name': 'Variable de subsistema',
                'verbose_name_plural': 'Variables de subsistema',
                'db_table': 'variables_subsistema',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteSubsistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador único dentro del subsistema. Ej: fijaciones_plus', max_length=80)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del componente', max_length=200)),
                ('formula_texto', models.TextField(help_text='Expresión aritmética Python. Puede usar variables de entrada y salidas previas. Ej: (total_powergrip * tornilleria) * desperdicio')),
                ('variable_salida', models.CharField(blank=True, default='', help_text='Si este componente produce un valor que otros componentes necesitan, indica aquí el nombre de esa variable. Ej: limpiador', max_length=80)),
                ('unidad', models.CharField(blank=True, default='', max_length=40)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoría de producto donde se seleccionará el material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componentes_subsistema', to='catalogos.categoriaproducto')),
                ('subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_db', to='ingenieria.subsistema')),
            ],
            options={
                'verbose_name': 'Componente de subsistema',
                'verbose_name_plural': 'Componentes de subsistema',
                'db_table': 'componentes_subsistema',
                'ordering': ['orden'],
                'unique_together': {('subsistema', 'codigo')},
            },
        ),
    ]
