# Generated by Django 4.2.29 on 2026-04-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0003_subsistema_apu_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentesubsistema',
            name='unidad_apu',
            field=models.CharField(blank=True, default='', help_text="Unidad de la referencia. Ej: 'soporte', 'm²', 'ml'.", max_length=40, verbose_name='Unidad APU'),
        ),
        migrations.AddField(
            model_name='componentesubsistema',
            name='variable_referencia_apu',
            field=models.CharField(blank=True, default='', help_text="Variable de entrada que actúa como denominador del rendimiento. Ej: 'total_powergrip'. Si se deja vacío, usa la configuración del subsistema.", max_length=80, verbose_name='Variable de referencia APU'),
        ),
        migrations.AlterField(
            model_name='subsistema',
            name='variable_referencia_apu',
            field=models.CharField(blank=True, default='', help_text="Nombre de la variable de entrada que representa la cantidad principal del sistema para el APU. Ej: 'total_powergrip'. Se usa como divisor para calcular el rendimiento por unidad. Si se deja vacío, se usa el área del proyecto.", max_length=80, verbose_name='Variable de referencia APU'),
        ),
    ]
