# Generated by Django 4.2.29 on 2026-04-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0004_componente_apu_campos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dependenciatecnica',
            table='dependencias_tecnicas',
        ),
        migrations.AlterModelTable(
            name='reglacalculo',
            table='reglas_calculo',
        ),
    ]
