# Generated by Django 4.2.29 on 2026-04-28 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_replace_rendimiento_with_precio_en_dolares'),
        ('ingenieria', '0005_alter_dependenciatecnica_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='tipo_sistema',
            field=models.CharField(choices=[('CONSTRUCTIVO', 'Sistema constructivo'), ('CONSUMO', 'Sistema de consumo')], default='CONSTRUCTIVO', help_text='Constructivo: receta técnica con componentes y fórmulas. Consumo: tabla de capas y consumo de producto.', max_length=20, verbose_name='Tipo de sistema'),
        ),
        migrations.AddField(
            model_name='subsistema',
            name='capas_parqueo',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Capas — Áreas de parqueo'),
        ),
        migrations.AddField(
            model_name='subsistema',
            name='capas_rampa',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Capas — Áreas de rampa/arranque/frenado'),
        ),
        migrations.AddField(
            model_name='subsistema',
            name='capas_transitable',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Capas — Áreas transitables'),
        ),
        migrations.AddField(
            model_name='subsistema',
            name='categoria_consumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsistemas_consumo', to='catalogos.categoriaproducto', verbose_name='Categoría de producto'),
        ),
        migrations.AddField(
            model_name='subsistema',
            name='consumo_por_capa',
            field=models.CharField(blank=True, default='', help_text='Ej: Aprox. 200-400 g/m²', max_length=200, verbose_name='Consumo por capa'),
        ),
        migrations.AddField(
            model_name='subsistema',
            name='consumo_prueba_transitable',
            field=models.CharField(blank=True, default='', help_text='Consumo para área de prueba en zonas transitables', max_length=200, verbose_name='Consumo prueba — Área transitable (por capa)'),
        ),
        migrations.AddField(
            model_name='subsistema',
            name='estado_producto',
            field=models.CharField(blank=True, choices=[('LIQUIDO', 'Líquido'), ('SOLIDO', 'Sólido'), ('ROLLOS', 'Rollos')], default='', help_text='Presentación física del producto: Líquido, Sólido o Rollos', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='subsistema',
            name='funcion',
            field=models.CharField(blank=True, default='', help_text='Ej: Imprimación, Impermeabilización, Capa intermedia', max_length=200, verbose_name='Función'),
        ),
        migrations.AddField(
            model_name='subsistema',
            name='resistencia_quimica',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Resistencia química'),
        ),
        migrations.AddField(
            model_name='subsistema',
            name='superficie',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Superficie de aplicación'),
        ),
        migrations.AddField(
            model_name='subsistema',
            name='temperatura',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Temperatura de aplicación'),
        ),
        migrations.AddField(
            model_name='subsistema',
            name='tipo_producto',
            field=models.CharField(blank=True, choices=[('BICOMPONENTE', 'Bicomponente'), ('MONOCOMPONENTE', 'Monocomponente')], default='', max_length=20, verbose_name='Tipo de producto'),
        ),
    ]
