# Generated by Django 4.2.29 on 2026-04-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0006_add_tipo_sistema_and_consumo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsistema',
            name='consumo_max_g_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Consumo máximo del producto por m² por capa. Ej: 400', max_digits=10, null=True, verbose_name='Consumo máximo (g/m² por capa)'),
        ),
        migrations.AddField(
            model_name='subsistema',
            name='consumo_min_g_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Consumo mínimo del producto por m² por capa. Ej: 200', max_digits=10, null=True, verbose_name='Consumo mínimo (g/m² por capa)'),
        ),
    ]
