# Generated by Django 4.2.29 on 2026-04-29 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_replace_rendimiento_with_precio_en_dolares'),
        ('ingenieria', '0009_consumo_architectural_correction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capaconsumo',
            options={'ordering': ['orden'], 'verbose_name': 'Capa de Consumo (deprecated)', 'verbose_name_plural': 'Capas de Consumo (deprecated)'},
        ),
        migrations.AlterField(
            model_name='capaconsumo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas_consumo', to='catalogos.categoriaproducto'),
        ),
        migrations.AlterField(
            model_name='capaconsumo',
            name='consumo_m2',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='capaconsumo',
            name='desperdicio_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='capaconsumo',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='capaconsumo',
            name='num_capas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='capaconsumo',
            name='requiere_accesorio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='capaconsumo',
            name='unidad',
            field=models.CharField(default='kg', max_length=40),
        ),
    ]
