# Generated by Django 4.2.29 on 2026-05-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0010_alter_capaconsumo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsistema',
            name='imagen_tecnica',
            field=models.ImageField(blank=True, help_text='Imagen técnica o diagrama del subsistema (opcional).', null=True, upload_to='ingenieria/subsistemas/imagenes_tecnicas/', verbose_name='Imagen técnica'),
        ),
        migrations.CreateModel(
            name='SubconjuntoRecetaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del grupo. Ej: Estructura metálica, Aislamiento térmico', max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subconjuntos_receta', to='ingenieria.subsistema')),
            ],
            options={
                'verbose_name': 'Subconjunto de Receta Técnica',
                'verbose_name_plural': 'Subconjuntos de Receta Técnica',
                'db_table': 'subconjuntos_receta_tecnica',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='componentesubsistema',
            name='subconjunto',
            field=models.ForeignKey(blank=True, help_text='Grupo al que pertenece este componente dentro de la receta técnica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componentes', to='ingenieria.subconjuntorecetatecnica', verbose_name='Subconjunto'),
        ),
    ]
