# Generated by Django 4.2.29 on 2026-05-06 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0011_subsistema_imagen_subconjunto_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespieceMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text="Nombre descriptivo opcional. Ej: 'Cubierta oficinas – Lote Norte'", max_length=200)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('GUARDADO', 'Guardado')], db_index=True, default='BORRADOR', max_length=20)),
                ('variables_entrada', models.JSONField(blank=True, default=dict, help_text='Snapshot de las variables ingresadas al momento del último cálculo/guardado.')),
                ('resultado_snapshot', models.JSONField(blank=True, default=list, help_text='Snapshot inmutable del resultado del cálculo (lista de líneas).')),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subconjuntos', models.ManyToManyField(blank=True, help_text='Subconjuntos de la receta técnica que se calculan en este despiece.', related_name='despieces', to='ingenieria.subconjuntorecetatecnica', verbose_name='Subconjuntos incluidos')),
                ('subsistema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despieces_maestro', to='ingenieria.subsistema', verbose_name='Subsistema')),
            ],
            options={
                'verbose_name': 'Despiece Maestro',
                'verbose_name_plural': 'Despieces Maestro',
                'db_table': 'despieces_maestro',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DespieceMaestroLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subconjunto_nombre', models.CharField(blank=True, default='General', max_length=200)),
                ('componente_codigo', models.CharField(max_length=80)),
                ('componente_nombre', models.CharField(blank=True, max_length=200)),
                ('formula_texto', models.TextField(blank=True)),
                ('cantidad_calculada', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('unidad', models.CharField(blank=True, max_length=40)),
                ('variable_salida', models.CharField(blank=True, max_length=80)),
                ('variable_referencia_apu', models.CharField(blank=True, max_length=80)),
                ('unidad_apu', models.CharField(blank=True, max_length=40)),
                ('categoria_nombre', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('despiece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ingenieria.despiecemaestro')),
                ('subconjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_despiece', to='ingenieria.subconjuntorecetatecnica')),
            ],
            options={
                'verbose_name': 'Línea de Despiece Maestro',
                'verbose_name_plural': 'Líneas de Despiece Maestro',
                'db_table': 'despieces_maestro_lineas',
                'ordering': ['orden'],
            },
        ),
    ]
