# Generated by Django 4.2.29 on 2026-05-06 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_replace_rendimiento_with_precio_en_dolares'),
        ('ingenieria', '0012_despiece_maestro'),
    ]

    operations = [
        migrations.AddField(
            model_name='despiecemaestrolinea',
            name='fecha_precio',
            field=models.DateTimeField(blank=True, help_text='Snapshot de fecha_actualizacion_precio del producto al guardar.', null=True),
        ),
        migrations.AddField(
            model_name='despiecemaestrolinea',
            name='moneda',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='despiecemaestrolinea',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='despiecemaestrolinea',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='despiecemaestrolinea',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto del catálogo seleccionado para este componente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_despiece_maestro', to='catalogos.producto'),
        ),
        migrations.AddField(
            model_name='despiecemaestrolinea',
            name='producto_codigo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='despiecemaestrolinea',
            name='producto_nombre',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
