# Generated by Django 4.2.29 on 2026-05-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0013_producto_snapshot_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='despiecemaestrolinea',
            name='cantidad_redondeada',
            field=models.IntegerField(blank=True, help_text='math.ceil(cantidad_calculada): unidades comerciales necesarias.', null=True),
        ),
    ]
