# Generated by Django 4.2.29 on 2026-05-07 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0015_proyecto_cliente_nombre_opcional'),
        ('ingenieria', '0014_cantidad_redondeada_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='despiecemaestro',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto comercial desde el que se originó este despiece (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despieces_maestro', to='comercial.proyecto', verbose_name='Proyecto asociado'),
        ),
    ]
