# Generated by Django 4.2.29 on 2026-05-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_replace_rendimiento_with_precio_en_dolares'),
        ('ingenieria', '0015_despiece_maestro_proyecto_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidacionDespieceMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Nombre final del material consolidado (editable por el usuario).', max_length=200)),
                ('lineas_ids', models.JSONField(default=list, help_text='PKs de DespieceMaestroLinea incluidas en este consolidado.')),
                ('cantidad_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('cantidad_redondeada', models.IntegerField(default=0)),
                ('unidad', models.CharField(blank=True, max_length=40)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('producto_codigo', models.CharField(blank=True, max_length=50)),
                ('producto_nombre', models.CharField(blank=True, max_length=300)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('moneda', models.CharField(blank=True, max_length=3)),
                ('fecha_precio', models.DateTimeField(blank=True, null=True)),
                ('despiece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidaciones', to='ingenieria.despiecemaestro')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidaciones_despiece', to='catalogos.producto')),
            ],
            options={
                'verbose_name': 'Consolidación de Despiece',
                'verbose_name_plural': 'Consolidaciones de Despiece',
                'db_table': 'despieces_maestro_consolidaciones',
                'ordering': ['orden'],
            },
        ),
    ]
