# Generated by Django 4.2.29 on 2026-05-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0017_variable_tipo_entrada_opciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='despiecemaestrolinea',
            name='valores_usados',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot de los valores usados al evaluar la fórmula de esta línea (variables de entrada + salidas intermedias). Permite reconstruir fórmula + valores + resultado sin depender de la receta actual.'),
        ),
        migrations.AddField(
            model_name='subsistema',
            name='notas_tecnicas',
            field=models.TextField(blank=True, default='', help_text='Notas técnicas de consulta para el usuario final. Se definen aquí y se muestran en el Despiece Maestro de este subsistema.', verbose_name='Notas técnicas'),
        ),
    ]
