# Generated by Django 4.2.29 on 2026-06-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0018_despiecemaestrolinea_valores_usados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableDependenciaSubsistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_origen', models.CharField(help_text='Valor concreto (string) de la variable origen que dispara la regla. Debe existir dentro de las opciones de la variable origen.', max_length=80, verbose_name='Valor origen')),
                ('valor_destino', models.CharField(help_text='Valor que se asignará a la variable destino. Debe existir en las opciones de la variable destino.', max_length=80, verbose_name='Valor destino')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('notas', models.CharField(blank=True, default='', max_length=200)),
                ('subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_variables', to='ingenieria.subsistema', verbose_name='Subsistema')),
                ('variable_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_como_destino', to='ingenieria.variablesubsistema', verbose_name='Variable destino')),
                ('variable_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_como_origen', to='ingenieria.variablesubsistema', verbose_name='Variable origen')),
            ],
            options={
                'verbose_name': 'Dependencia entre variables',
                'verbose_name_plural': 'Dependencias entre variables',
                'db_table': 'variable_dependencia_subsistema',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='variabledependenciasubsistema',
            constraint=models.CheckConstraint(check=models.Q(('variable_origen', models.F('variable_destino')), _negated=True), name='dep_var_origen_distinto_destino'),
        ),
        migrations.AlterUniqueTogether(
            name='variabledependenciasubsistema',
            unique_together={('subsistema', 'variable_origen', 'valor_origen', 'variable_destino')},
        ),
    ]
