# Generated by Django 4.2.29 on 2026-06-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0019_variabledependenciasubsistema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesubsistema',
            name='participa_en_base_apu',
            field=models.BooleanField(default=False, help_text='Si está marcado, el valor ingresado por el usuario en esta variable se suma a la base del rendimiento del APU (area_base_apu). No usar para porcentajes ni opciones únicas.', verbose_name='Participa en base APU'),
        ),
    ]
