# Generated by Django 4.2.29 on 2026-07-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0020_variablesubsistema_participa_en_base_apu'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentesubsistema',
            name='requiere_presentacion_producto',
            field=models.BooleanField(default=False, help_text="Si está activo, la cantidad se calcula después de elegir el producto, usando su campo 'cantidad_presentacion'.", verbose_name='Calcular después de seleccionar producto'),
        ),
        migrations.AddField(
            model_name='componentesubsistema',
            name='variable_presentacion_producto',
            field=models.CharField(blank=True, default='', help_text="Nombre de la variable que recibirá el valor de 'cantidad_presentacion'. Debe ser un identificador Python válido y estar presente en la fórmula. Obligatorio cuando 'requiere_presentacion_producto' está activo.", max_length=80, verbose_name='Variable de presentación'),
        ),
    ]
