# Generated by Django 4.2.29 on 2026-03-20 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion_precio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última actualización de precio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Precio actual (COP)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_directos', to='catalogos.proveedor', verbose_name='Proveedor principal'),
        ),
    ]
