# Generated by Django 4.2.29 on 2026-03-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_categoria_imagen'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE productos SET fecha_actualizacion_precio = NOW() WHERE fecha_actualizacion_precio IS NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_actualizacion_precio',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_actual',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_principales', to='catalogos.proveedor'),
        ),
    ]
