# Generated by Django 4.2.29 on 2026-03-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_producto_proveedor_precio_directo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='moneda',
            field=models.CharField(choices=[('COP', 'COP'), ('USD', 'USD'), ('EUR', 'EUR')], default='COP', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Precio actual'),
        ),
    ]
