# Generated by Django 4.2.29 on 2026-04-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_producto_unidades_por_presentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='rendimiento',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_en_dolares',
            field=models.BooleanField(default=False, help_text='Si está activo, el precio del producto está en USD y se dividirá por la TRM del proyecto al calcular el despiece.', verbose_name='Precio en dólares (USD)'),
        ),
    ]
