# Generated by Django 4.2.29 on 2026-06-11 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_replace_rendimiento_with_precio_en_dolares'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ancho_presentacion',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Ancho'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_presentacion',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Ej: 92.96 (área total m² de un rollo 3.05 x 30.48).', max_digits=14, null=True, verbose_name='Cantidad por presentación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='largo_presentacion',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Largo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='presentacion_nombre',
            field=models.CharField(blank=True, default='', help_text="Ej: 'Rollo 3.05 x 30.48 m', 'Lámina 1.00 x 3.00 m', 'Caja x 100 und'.", max_length=200, verbose_name='Nombre de presentación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_dimension',
            field=models.CharField(blank=True, choices=[('m', 'metros (m)'), ('cm', 'centímetros (cm)'), ('mm', 'milímetros (mm)'), ('ft', 'pies (ft)'), ('in', 'pulgadas (in)')], default='', help_text='Unidad de ancho/largo (m, cm, mm, ft, in).', max_length=4, verbose_name='Unidad de dimensión'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_presentacion',
            field=models.ForeignKey(blank=True, help_text='Unidad en la que se expresa la cantidad por presentación (m², m, und, gal).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_unidad_presentacion', to='catalogos.unidadmedida', verbose_name='Unidad de presentación'),
        ),
    ]
