# Generated by Django 4.2.29 on 2026-03-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='aiu_pct',
            field=models.DecimalField(decimal_places=4, default=130, max_digits=8),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='margen_comercial_pct',
            field=models.DecimalField(decimal_places=4, default=130, max_digits=8),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='motivo_devolucion',
            field=models.TextField(blank=True, help_text='Motivo de rechazo o devolución por parte del Administrador o Compras', null=True),
        ),
    ]
