# Generated by Django 4.2.29 on 2026-03-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_redesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsistema',
            name='accion',
            field=models.CharField(help_text='Código de acción: CREAR_SOLICITUD, CREAR_VERSION, SUBIR_ARCHIVO, etc.', max_length=100, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='proyectoarchivo',
            name='nombre',
            field=models.CharField(help_text='Nombre descriptivo del archivo', max_length=300, verbose_name='Nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre',
            field=models.CharField(max_length=300, verbose_name='Nombre / descripción'),
        ),
    ]
