# Generated by Django 4.2.29 on 2026-03-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuariosistema_rol_and_more'),
        ('comercial', '0003_alter_logsistema_accion_alter_proyectoarchivo_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='solicitudes/archivos/%Y/%m/', verbose_name='Archivo')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre del archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='comercial.solicitud', verbose_name='Solicitud')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_solicitud', to='usuarios.usuariosistema', verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Archivo de solicitud',
                'verbose_name_plural': 'Archivos de solicitud',
                'db_table': 'solicitudes_archivos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.RemoveField(
            model_name='proyectoarchivo',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='proyectoarchivo',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='logsistema',
            name='accion',
            field=models.CharField(help_text='Código de acción: CREAR_SOLICITUD, SUBIR_ARCHIVO, etc.', max_length=100, verbose_name='Acción'),
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
        migrations.DeleteModel(
            name='ProyectoArchivo',
        ),
        migrations.DeleteModel(
            name='TipoProyecto',
        ),
    ]
