# Generated by Django 4.2.29 on 2026-03-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuariosistema_rol_and_more'),
        ('comercial', '0004_solicitudarchivo_remove_proyectoarchivo_proyecto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipos_proyecto',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_proyecto', models.DateField(auto_now_add=True)),
                ('area_total_m2', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('perimetro_ml', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('trm', models.DecimalField(decimal_places=4, default=4200, max_digits=14)),
                ('margen_comercial_pct', models.DecimalField(decimal_places=4, default=130, max_digits=8)),
                ('iva_pct', models.DecimalField(decimal_places=4, default=19, max_digits=8)),
                ('aiu_pct', models.DecimalField(decimal_places=4, default=130, max_digits=8)),
                ('moneda', models.CharField(choices=[('COP', 'COP'), ('USD', 'USD'), ('EUR', 'EUR')], default='COP', max_length=3)),
                ('aplica_exencion_iva', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('SOLICITUD', 'Solicitud'), ('DESPIECE', 'Despiece'), ('EN_REVISION_COMPRAS', 'En revisión de precios (Compras)'), ('DESPIECE_VALIDADO', 'Despiece validado'), ('APU', 'APU en proceso'), ('APU_GENERADO', 'APU enviado a revisión'), ('COTIZADO', 'Cotizado'), ('APROBADO', 'Aprobado'), ('CERRADO', 'Cerrado'), ('ANULADO', 'Anulado')], default='SOLICITUD', max_length=25)),
                ('motivo_devolucion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='comercial.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_creados', to='usuarios.usuariosistema')),
                ('solicitud', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyecto', to='comercial.solicitud')),
                ('tipo_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='comercial.tipoproyecto')),
            ],
            options={
                'db_table': 'proyectos',
            },
        ),
    ]
