# Generated by Django 4.2.29 on 2026-03-26 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_restaurar_tipoproyecto_proyecto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-version']},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='es_version_actual',
            field=models.BooleanField(db_index=True, default=True, help_text='Solo una versión por solicitud puede ser la actual', verbose_name='Es versión actual'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Número de versión dentro de la solicitud', verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='comercial.solicitud'),
        ),
    ]
