# Generated by Django 4.2.29 on 2026-03-31 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_versionar_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='comercial.solicitud'),
        ),
    ]
