# Generated by Django 4.2.29 on 2026-04-09 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_alter_configuracionsistema_id_and_more'),
        ('comercial', '0010_update_state_usuario_to_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsistema',
            name='configuracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='configuracion.configuracionsistema'),
        ),
        migrations.AlterField(
            model_name='solicitudarchivo',
            name='configuracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_solicitud', to='configuracion.configuracionsistema', verbose_name='Subido por'),
        ),
    ]
