# Generated by Django 4.2.29 on 2026-04-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0012_rename_usuario_to_configuracion_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='unidad_negocio',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Unidad a la que pertenece este cliente. Se asigna automáticamente al crear.', max_length=20, verbose_name='Unidad de negocio'),
        ),
    ]
