# Generated by Django 4.2.29 on 2026-05-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0015_proyecto_cliente_nombre_opcional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='area_total_m2',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='perimetro_ml',
        ),
    ]
