# Generated by Django 4.2.29 on 2026-05-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0016_remove_proyecto_area_total_m2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_GESTION', 'En gestión'), ('EN_PRESUPUESTO', 'En presupuesto'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CERRADA', 'Cerrada')], default='EN_GESTION', max_length=20),
        ),
    ]
