# Generated by Django 4.2.29 on 2026-06-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0017_alter_solicitud_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre comercial. Ej: 'Garantía 10 años — Membrana TPO'.", max_length=120)),
                ('duracion_meses', models.PositiveIntegerField(default=12, help_text='Duración en meses. Ej: 120 para 10 años.')),
                ('descripcion', models.CharField(blank=True, default='', help_text='Descripción corta visible junto al nombre.', max_length=300)),
                ('condiciones', models.TextField(blank=True, default='', help_text='Condiciones y exclusiones detalladas (texto largo).')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de garantía',
                'verbose_name_plural': 'Tipos de garantía',
                'db_table': 'tipos_garantia',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
