# Generated by Django 4.2.29 on 2026-06-12 16:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0018_tipogarantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipogarantia',
            name='porcentaje_recargo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Porcentaje de recargo comercial aplicado sobre Materiales. Ej: 5.00 = 5%.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='tipogarantia',
            name='duracion_meses',
            field=models.PositiveIntegerField(blank=True, help_text='(Legacy Fase 9) Duración en meses. Oculto en el formulario actual.', null=True),
        ),
    ]
