# Generated by Django 4.2.29 on 2026-06-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0019_tipogarantia_porcentaje_recargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='motivo_devolucion',
            field=models.TextField(blank=True, default='', help_text='Motivo registrado por el aprobador cuando devuelve la solicitud para ajustes.'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_GESTION', 'En gestión'), ('EN_PRESUPUESTO', 'En presupuesto'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('DEVUELTA', 'Devuelta'), ('RECHAZADA', 'Rechazada'), ('CERRADA', 'Cerrada')], default='EN_GESTION', max_length=20),
        ),
    ]
