# Generated by Django 4.2.29 on 2026-08-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0032_eliminar_garantia'),
        ('comercial', '0020_solicitud_motivo_devolucion_alter_solicitud_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoGarantia',
        ),
    ]
