# Generated by Django 4.2.29 on 2026-08-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0021_eliminar_garantia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='trm',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='TRM contractual del proyecto. Se precarga con la TRM global al crear; queda congelada para este proyecto.', max_digits=14, null=True),
        ),
    ]
